fix: vertically centering loading spinner in the animated class
Spiderpig86/Cirrus pull request #167
Opened 2023-04-09 13:31 UTC by bjorndonald

# Description

I noticed that the loading spinner is not fully vertically centered. So I made a single line adjustment to the animation.scss. And changed the means of calculating the top property.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

**Test Configuration**:
* Firmware version: macOS Monterey Version 12.6
* Hardware: Macbook Pro
* Toolchain: VSCode

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2023-05-30 00:54 UTC, Spiderpig86 commented
Thanks for creating a PR! I have taken a look and left a comment.

2023-06-21 05:23 UTC, Spiderpig86 requested changes

2023-06-22 12:24 UTC, bjorndonald commented on src/base/animations.scss
> +            top: calc(50% - ((1rem + 2px) / 2));
Alright that works

2023-12-18 02:41 UTC, Spiderpig86 commented
Closing. Moved to https://github.com/Spiderpig86/Cirrus/pull/242

2023-12-18 02:41 UTC, closed without merging