New group rounded feature and small color fix control themes
Spiderpig86/Cirrus pull request #49
Opened 2020-11-12 08:43 UTC by FlorianWoelki

# Description

Sorry for so much PR's :D 

I've added a common use case for actual rounding group tags. I think it should be pretty useful for some use cases. Furthermore, there are rounded tags so why not having grouped rounded tags ;)

In addition, I've added the primary color to the control themes. This fix resolved that primary colored closing tags are not clickable.

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# How Has This Been Tested?

You can see the result of the new rounded grouping tags in the image below:
![image](https://user-images.githubusercontent.com/20746070/98916255-3a4cba00-24cb-11eb-9402-07076fbdef8f.png)

1. tag container without grouped or rounded
2. grouped tag container
3. grouped and rounded tag container

2020-11-14 06:58 UTC, Spiderpig86 requested changes
Overall, thanks for the new addition of the tags. I see you're hard at work on adding some new things which are welcome. Please address the comments and I'll review again.

2020-11-14 06:58 UTC, Spiderpig86 commented on src/ext/tags.scss
> +    &.group-tags {
Can be ignored, Cirrus uses 4 spaces.

2020-11-14 06:58 UTC, Spiderpig86 commented on src/ext/tags.scss
> +        &.group-rounded {
To try to stick to BEM naming conventions moving forward, we should name this `group-tags--rounded`.

2020-11-14 06:58 UTC, Spiderpig86 commented on src/ext/tags.scss
> +                border-radius: 290486px 0 0 290486px;
Ignore

2020-11-14 06:58 UTC, Spiderpig86 commented on src/ext/tags.scss
> +                border-radius: 0 290486px 290486px 0;
Ignore, but curious as to how you arrived at `290486px`. It's fine as it stands.

2020-11-14 06:58 UTC, Spiderpig86 commented on src/ext/tags.scss
> +            }
Add a new line here.

2020-11-14 06:58 UTC, Spiderpig86 commented on src/ext/tags.scss
> +            margin-right: 0 !important;
Ignore, might need to restart the on-going campaign the number of `!important` used.

2020-11-14 06:58 UTC, Spiderpig86 commented on src/ext/tags.scss
> +                border-radius: 0.25rem 0 0 0.25rem;
Ignore

2020-11-14 06:58 UTC, Spiderpig86 commented on src/ext/tags.scss
> +
Extra spacing here. Remove.

2020-11-14 06:58 UTC, Spiderpig86 commented on src/ext/tags.scss
> +
Same as above.

2020-11-14 06:58 UTC, Spiderpig86 commented on src/ext/tags.scss
> +                border-radius: 0 0.25rem 0.25rem 0;
Ignore

2020-11-14 07:59 UTC, FlorianWoelki commented on src/ext/tags.scss
> +                border-radius: 0 290486px 290486px 0;
You've defined it for the rounded border radius tag ^^

2020-11-15 00:22 UTC, Spiderpig86 approved these changes
Looks good!

2020-11-15 00:23 UTC, merged